<?php

namespace MyAppsSdk\Test\Context;

use MyAppsSdk\Context\Hotspot;
use PHPUnit_Framework_TestCase;

class HotspotTest extends PHPUnit_Framework_TestCase
{

    private $preAuthData;

    private $postAuthData;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->preAuthData = json_decode(file_get_contents(__DIR__ . "/../samples/pre-auth.json"), true)['data']['hotspot'];

        $this->postAuthData = json_decode(file_get_contents(__DIR__ . "/../samples/post-auth.json"), true)['data']['hotspot'];
        ;
    }


    public function testId()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("9067", $hotspot->getId());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("9067", $hotspot->getId());
    }

    public function testName()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("MainAp", $hotspot->getName());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("MainAp", $hotspot->getName());
    }

    public function testCity()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("FLORENCE, Italy", $hotspot->getCity());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("FLORENCE, Italy", $hotspot->getCity());
    }

    public function testIdentifier()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("685112345D_main", $hotspot->getIdentifier());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("685112345D_main", $hotspot->getIdentifier());
    }

    public function testLatitude()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("45.960782503827", $hotspot->getLatitude());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("45.960782503827", $hotspot->getLatitude());
    }

    public function testLongitude()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("12.091283106750", $hotspot->getLongitude());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("12.091283106750", $hotspot->getLongitude());
    }

    public function testMacAddress()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("685112345D", $hotspot->getMacAddress());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("685112345D", $hotspot->getMacAddress());
    }

    public function testState()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("Florence", $hotspot->getState());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("Florence", $hotspot->getState());
    }

    public function testTag()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("hotspot", $hotspot->getTag());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("hotspot", $hotspot->getTag());
    }

    public function testZip()
    {
        $hotspot = new Hotspot($this->preAuthData);
        $this->assertEquals("55100", $hotspot->getZip());

        $hotspot = new Hotspot($this->postAuthData);
        $this->assertEquals("55100", $hotspot->getZip());
    }
}
